In [1]:
import sys
# Add Python Tools
pythonToolsDir = r'J:\Projects\JHUTrabeculae\Software\Python\PythonTools'
sys.path.append(pythonToolsDir)

# Add ctk-cli
ctkcli_DIR = r'J:\Projects\JHUTrabeculae\Software\Python\ctk-cli'
sys.path.append(ctkcli_DIR)

# Add TrabeculaeTools
TrabeculaeTools_DIR = r'J:\Projects\JHUTrabeculae\Software\Python\TrabeculaeTools'
sys.path.append(TrabeculaeTools_DIR)

from ImageJTools import macroImageJ
from ImageJTools.HelperBoneJ import joinBoneJResults, extractSquareRoIs, maskImage, randomTransformation, getSimilarityMetrics

from PythonTools import registration, transforms, transformations
from PythonTools.helpers import vtk as vtkhelper
from PythonTools.helpers.elastix import elastix as elastixhelper
from PythonTools import io


import vtk
import matplotlib
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage
import math
import os
import time
import seaborn as sns


import seaborn as sns
import pandas as pd

import SimpleITK as sitk



imagePathTarget=r'' 
RoIparameters= r''
roiImageFilepath= r''
imagePathMoving= r''
registrationFile= r''

In [2]:
import numpy as np

In [17]:
points = np.random.rand(8,3)

print points

T = np.eye(3)

T[0,0]= -1
#T[1,3]= 3

points2 = np.dot(points, T) + [0,3,4]

print points2

[[ 0.21337534  0.46591998  0.57883575]
 [ 0.58376438  0.43819118  0.39640364]
 [ 0.60088871  0.11340592  0.47399412]
 [ 0.31868903  0.78252104  0.76033453]
 [ 0.99459901  0.12895316  0.92255864]
 [ 0.21649242  0.28929819  0.76449965]
 [ 0.75102411  0.26286543  0.61384395]
 [ 0.16831335  0.0052338   0.38052923]]
[[-0.21337534  3.46591998  4.57883575]
 [-0.58376438  3.43819118  4.39640364]
 [-0.60088871  3.11340592  4.47399412]
 [-0.31868903  3.78252104  4.76033453]
 [-0.99459901  3.12895316  4.92255864]
 [-0.21649242  3.28929819  4.76449965]
 [-0.75102411  3.26286543  4.61384395]
 [-0.16831335  3.0052338   4.38052923]]
